config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path: "admin/admins",
  skip: [:registrations, :passwords],
  controllers: {
    sessions: "admin/admins/sessions"
  }

  # 管理者とユーザーで区別
  devise_for :users, controllers: {
    sessions: "public/users/sessions",
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations',
  }

  scope module: :public do
    get "search" => "searches#search"
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update,]
    resources :posts, only: [:index, :update, :new, :destroy, :edit, :create, :show] do
      resource :youtube_urls, only: [:edit, :update]
      resource :bookmarks, only: [:show, :create, :destroy]
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :comments, only: [:destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :users, only: [:show, :edit, :update]
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :genres, only: [:index, :update, :create, :destroy, :edit]
    get 'homes/top'
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "public/users/sessions#guest_sign_in"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!

  def search
    @range = params[:range]
    @word = params[:word]

    if @word.blank?
      flash[:notice] = "入力が必要です。"
      redirect_to request.referer
    else

      if @range == "User"
        @users = User.looks(@word, true)
      else
        @posts = Post.looks(@word)
      end
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/views/admin/searches/_search.html.erb
<% if admin_signed_in? %>
  <div class="search_form">
    <%= form_with url: admin_search_path, local: true, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([['User'], ['Post']]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/admin/searches/search.html.erb
<div class="text-right mt-3">
  <%= render 'admin/searches/search' %>
</div>
<h2>検索結果</h2>
<table class="table table-hover table-inverse">
  <!-- 検索対象モデルがUserの時 -->
  <% if @range == "User" %>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <!-- ユーザーのアバター写真 -->
          <td><%= image_tag user.get_avatar(70, 70) %></td>
          <!-- 氏名 -->
          <td>
            <%= link_to admin_user_path(user) do %>
              <%= user.family_name %> &nbsp;&nbsp; <%= user.first_name %>
            <% end %>
          </td>
          <!-- ユーザーが生徒または家族かどうか -->
          <td><%= user.is_member ? '生徒' : '家族' %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!-- 検索対象モデルがPostの時-->
    <tbody>
      <tr>
        <th class="col-1">日時</th>
        <th class="col-2">ユーザー</th>
        <th class="col-2">ジャンル</th>
        <th class="col-1">コメント</th>
        <th class="colspan-7">投稿</th>
      </tr>

      <% @posts.each do |post| %>
        <tr>
          <!-- 投稿の作成日時 -->
          <td class="col-1"><%= post.created_at.strftime("%Y/%m/%d") %></td>
          <!-- 投稿のユーザー -->
          <td><%= link_to admin_user_path(post.user) do %>
            <%= post.user.family_name %> <%= post.user.first_name %>
          <% end %></td>
          <!-- 投稿のジャンル名 -->
          <td><%= post.genre.name %></td>
          <!-- 投稿のコメント -->
          <td><%= post.content %></td>
          <td>
            <!-- 投稿に添付された画像の表示 -->
            <% if post.images.attached? %>
              <% post.images.each do |image| %>
                <%= image_tag image, class: "aspect-ratio" %>
              <% end %>
            <% end %>
          </td>
          <td>
            <!-- 投稿に添付されたYouTube動画の埋め込み -->
            <% if post.youtube_url.present? %>
              <% post.youtube_url.path.split(/\R/).each do |url| %>
                <iframe width="224" height="126" src="https://www.youtube.com/embed/<%= url.last(11) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
              <% end %>
            <% end %>
          </td>
          <td>
            <!-- 投稿の削除ボタン -->
            <%= link_to "削除", admin_post_path(post), method: :delete, class: "btn btn-danger float-right", data: { confirm: "削除しますか？" } %>
          </td>
          <td>
            <%= link_to admin_post_path(post.id) do %>
              <i class="fa-solid fa-arrow-right"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>