config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path: "admin/admins",
  skip: [:registrations, :passwords],
  controllers: {
    sessions: "admin/admins/sessions"
  }

  # 管理者とユーザーで区別
  devise_for :users, controllers: {
    sessions: "public/users/sessions",
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations',
  }

  scope module: :public do
    get "search" => "searches#search"
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update,]
    resources :posts, only: [:index, :update, :new, :destroy, :edit, :create, :show] do
      resource :youtube_urls, only: [:edit, :update]
      resource :bookmarks, only: [:show, :create, :destroy]
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :comments, only: [:destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :users, only: [:show, :edit, :update]
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :genres, only: [:index, :update, :create, :destroy, :edit]
    get 'homes/top'
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "public/users/sessions#guest_sign_in"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="text-right">
  <%= render 'admin/searches/search' %>
</div>
<div class="container mt-5">
  <h2>会員一覧</h2>
  <div class="row table-hover">
    <table class="table col-12 mx-auto">
      <thead>
        <tr>
          <th>氏名</th>
          <th>表示名</th>
          <th>家族/生徒</th>
          <th>属柄</th>
          <th>会員状態</th>
          <th>編集</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= link_to admin_user_path(user) do %>
                <%= user.family_name %> &nbsp;&nbsp; <%= user.first_name %>
              <% end %>
            </td>
            <td><%= user.disply_name %></td>
            <td><%= user.is_member ? '生徒' : '家族' %></td>
            <td><%= user.family_relationship %></td>
            <td>
              <% if user.is_deleted == false %>
                <p class="text-success font-weight-bold">有効</p>
              <% else %>
                <p class="text-danger font-weight-bold">退会済み</p>
              <% end %>
            </td>
            <td>
              <% unless user.is_deleted %>
                <%= link_to "編集", edit_admin_user_path(user.id), class: "btn btn-success", style: "border-radius: 6px;" %>
              <% end %>
              <% unless user.is_deleted %>
                <%= link_to "退会", admin_withdrawal_path(user), method: :patch, class: "btn btn-danger", style: "border-radius: 6px;", data: { confirm: "本当に退会しますか？" } %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>