config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path: "admin/admins",
  skip: [:registrations, :passwords],
  controllers: {
    sessions: "admin/admins/sessions"
  }

  # 管理者とユーザーで区別
  devise_for :users, controllers: {
    sessions: "public/users/sessions",
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations',
  }

  scope module: :public do
    get "search" => "searches#search"
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update,]
    resources :posts, only: [:index, :update, :new, :destroy, :edit, :create, :show] do
      resource :youtube_urls, only: [:edit, :update]
      resource :bookmarks, only: [:show, :create, :destroy]
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :comments, only: [:destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :users, only: [:show, :edit, :update]
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :genres, only: [:index, :update, :create, :destroy, :edit]
    get 'homes/top'
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "public/users/sessions#guest_sign_in"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_one :youtube_url, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  validates :content, presence: true

  validates :images, presence: true, if: -> { youtube_url.blank? }
  validates :youtube_url, presence: true, if: -> { images.blank? }

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法分岐
  def self.looks(word)
    @posts = Post.where("content LIKE ?", "%#{word}%")
    if @posts.empty?
      @posts = Post.all
    end
    return @posts
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if(params[:genre_id])
      @posts = Post.where(genre_id: params[:genre_id]).order(created_at: :desc)
    else
      @posts = Post.order(created_at: :desc)
    end
       @genres = Genre.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to request.referer
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="text-right mt-3">
  <%= render 'admin/searches/search' %>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
      <table class="table table-hover table-bordered mt-5">
        <thead>
          <tr>
            <th>ジャンル検索</th>
          </tr>
        </thead>
        <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= link_to genre.name, admin_posts_path(genre_id: genre.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-10">
      <div class="text-center">
        <h2>投稿一覧</h2>
      </div>
      
      <% if @posts.present? %>
        <% @posts.each do |post| %>
          <div class="row border-bottom">
            <div class="col-3 mt-3">
              <%= render 'admin/users/user_info', user: post.user %>
            </div>
            <div class="col-7 pt-3">
              <p><%= post.created_at.strftime("%Y/%m/%d") %>&nbsp;&nbsp;<%= post.content %></p>
              <p>ジャンル名: <%= post.genre.name %></p>
              
              <!-- 写真 -->
              <div class="d-flex flex-wrap">
                <% if post.images.attached? %>
                  <% post.images.each do |image| %>
                    <div class="mr-3 mb-3">
                      <%= image_tag image, class: "index-img" %>
                    </div>
                  <% end %>
                <% end %>
              </div><br>

              <!-- ユーチューブ -->
              <div class="d-flex flex-wrap">
                <% if post.youtube_url.present? %>
                  <% post.youtube_url.path.split(/\R/).each do |url| %>
                    <div class="mr-3 mb-3">
                      <iframe width="224" height="126" src="https://www.youtube.com/embed/<%= url.last(11) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                    </div>
                  <% end %>
                <% end %>
              </div>
            
              <!-- 投稿についたコメント -->
              <div class="col-12">
                <p>
                  <% if post.comments.count > 0 %>
                    <i class="fas fa-comment" style="color: #48350e;"></i>
                  <% else %>
                    <i class="far fa-comment" style="color: #48350e;"></i>
                  <% end %>
                  <%= link_to post.comments.count, admin_post_path(post.id) %>
                </p>
              </div>
            
              <div class="float-right mb-3">
                <%= link_to "削除", admin_post_path(post), method: :delete, class: "btn btn-danger", data: { confirm: "削除しますか？" } %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
        該当する投稿はありませんでした
      <% end %>
    </div>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-3 pt-3">
      <%= render 'admin/users/user_info', user: @post.user %>
    </div>
    
    <div class="col-9">
      
      <!-- ポスト情報表示 -->
      <p><%= @post.created_at.strftime("%Y/%m/%d") %> &nbsp;&nbsp; <%= @post.content %></p>
      <p>ジャンル名:<%= @post.genre.name %></p>
      
      <!-- 写真表示 -->
      <div class="d-flex flex-wrap">
        <% if @post.images.attached? %>
          <% @post.images.each do |image| %>
            <div class="mr-3 mb-3">
              <%= image_tag image, class: "show-img" %>
            </div>
          <% end %>
        <% end %><br>
      </div>
      
      <!-- ユーチューブ動画表示 -->
      <div class="d-flex flex-wrap">
        <% if @post.youtube_url.present? %>
          <% @post.youtube_url.path.split(/\R/).each do |url| %>
            <div class="mr-3 mb-3">
              <iframe width="224" height="126" src="https://www.youtube.com/embed/<%= url.last(11) %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          <% end %>
        <% end %>
      </div>

      <!-- 投稿についたコメント -->
      <table class="table col-12 mx-auto table-hover">
        <thead>
          <tr>
            <th>日時</th>
            <th>氏名</th>
            <th>コメント</th>
            <th>削除</th>
          </tr>
        </thead>
        <tbody>
          <% if @post.comments.present? %>
            <h4>コメント(<%= @post.comments.count %>)</h4>
            <% @post.comments.each do |comment| %>
              <tr>
                <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
                <td><%= comment.user.family_name %> &nbsp;&nbsp; <%= comment.user.first_name %></td>
                <td><%= comment.content %></td>
                <td><%= link_to "削除", admin_comment_path(comment), method: :delete, class: "btn btn-danger", data: { confirm: "削除しますか？" } %></td>
              </tr>
            <% end %>
          <% else %>
            <tr>
              <td colspan="4" style="text-align: center; font-size: 20px;">この投稿にはまだコメントがありません。</td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>