config/routes.rb
Rails.application.routes.draw do


  devise_for :admins, path: "admin/admins",
  skip: [:registrations, :passwords],
  controllers: {
    sessions: "admin/admins/sessions"
  }

  # 管理者とユーザーで区別
  devise_for :users, controllers: {
    sessions: "public/users/sessions",
    passwords: 'public/users/passwords',
    registrations: 'public/users/registrations',
  }

  scope module: :public do
    get "search" => "searches#search"
    root to: 'homes#top'
    resources :users, only: [:show, :edit, :update,]
    resources :posts, only: [:index, :update, :new, :destroy, :edit, :create, :show] do
      resource :youtube_urls, only: [:edit, :update]
      resource :bookmarks, only: [:show, :create, :destroy]
      resources :comments, only: [:create]
      resource :favorites, only: [:create, :destroy]
    end
  end

  namespace :admin do
    get "search" => "searches#search"
    resources :comments, only: [:destroy]
    resources :posts, only: [:index, :show, :destroy]
    resources :users, only: [:show, :edit, :update]
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :genres, only: [:index, :update, :create, :destroy, :edit]
    get 'homes/top'
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "public/users/sessions#guest_sign_in"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  
  validates :name, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :genre
  has_one :youtube_url, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  validates :content, presence: true

  validates :images, presence: true, if: -> { youtube_url.blank? }
  validates :youtube_url, presence: true, if: -> { images.blank? }

  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # 検索方法分岐
  def self.looks(word)
    @posts = Post.where("content LIKE ?", "%#{word}%")
    if @posts.empty?
      @posts = Post.all
    end
    return @posts
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :bookmarks, dependent: :destroy

  has_many :favorites, dependent: :destroy

  has_one_attached :avatar
  validates :is_member, inclusion: { in: [true, false] }
  validates :family_name, presence: true
  validates :first_name, presence: true
  validates :disply_name, presence: true
  validates :family_relationship, presence: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

  # ユーザーのアバター
  def get_avatar(width, height)
    unless avatar.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      avatar.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    avatar.variant(resize_to_limit: [width, height]).processed
  end

  def commented_on?(post)
    comments.exists?(post_id: post.id)
  end

   # 検索方法分岐
  def self.looks(word, is_admin)
    if is_admin
      @users = where("first_name LIKE ?", "%#{word}%")
                .or(where("family_name LIKE ?", "%#{word}%"))
    else
      @users = where("disply_name LIKE ?", "%#{word}%")
    end

    if @users.empty?
      @users = User.all
    end
    @users = @users.where(is_deleted: false)
    return @users
  end

  # ゲスト
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.family_name = "guest"
      user.first_name = "user"
      user.is_member = false
      user.disply_name = "ゲストユーザー"
      user.family_relationship = "ゲスト"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end
end

app/models/youtube_url.rb
class YoutubeUrl < ApplicationRecord
  belongs_to :post
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  
  def top
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    if(params[:genre_id])
      @posts = Post.where(genre_id: params[:genre_id]).order(created_at: :desc)
    else
      @posts = Post.order(created_at: :desc)
    end
       @genres = Genre.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to request.referer
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "変更しました。"
       redirect_to admin_homes_top_path
    else
      flash[:notice] = "変更に失敗しました。"
      render :edit
    end
  end

  def withdrawal
    @user = User.find(params[:id])
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    flash[:notice] = "退会処理を実行いたしました"
    redirect_to admin_homes_top_path
  end

  private
  
  def user_params
    params.require(:user).permit(:family_name, :first_name, :disply_name, :family_relationship, :is_member)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  # ユーザー
  def after_sign_in_path_for(resource)
    case resource
    when User
      user_path(current_user)
    when Admin
      admin_homes_top_path
    end
  end
  
  def after_sign_out_path_for(resource)
    case resource
    when :user
      root_path
    when :admin
      new_admin_session_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :family_relationship, :disply_name, :is_member])
  end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cheemmate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c067b314d4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #000066;">
      <div class="container">
        <h4 style="color: #CCCC00;">Cheemmate</h4>
        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="background-color: #C0C0C0;">
          <span class="navbar-toggler-icon" style="background-color: #C0C0C0;"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            

            <% if user_signed_in? %>

              <p class="navbar-text mx-auto pr-5 text-light font-weight-bold" >ようこそ、<%= current_user.disply_name %> さん！</p>

              <li class="nav-item">
                <%= link_to "マイページ", user_path(current_user),class:"nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "ブックマーク一覧", post_bookmarks_path(current_user),class:"nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規投稿", new_post_path,class:"nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", posts_path,class:"nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete,class:"nav-link text-light" %>
              </li>
              

            <% elsif admin_signed_in? %>
             <!--管理者ログイン時のメニュー -->
              <li class="nav-item">
                <%= link_to "ジャンル一覧", admin_genres_path,class:"nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "会員一覧", admin_homes_top_path,class:"nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿一覧", admin_posts_path,class:"nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete,class:"nav-link text-light" %>
              </li> 
            <% elsif params[:controller] == "admin/admins/sessions" && params[:action]== "new" %>
            <% else %>
              <!-- ログイン前 -->
              <li>
                <%= link_to "ログイン", new_user_session_path, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "新規登録", new_user_registration_path, class: "nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to "ゲストログイン", users_guest_sign_in_path, class: "nav-link text-light", method: :post  %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= flash[:notice] %>
    <%= yield %>

    <footer style="background-color: #000066;">
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p class="text-light">お問合せはこちらまで：000-000-0000</p>
          </div>
        </div>
      </div>
    </footer>
  </body>


</html>